# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20190603_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(null=True, upload_to='hoodimage/'),
        ),
    ]
