# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_neighbourhood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
