# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20190604_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(null=True, upload_to='hoodimage/'),
        ),
    ]
