# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_auto_20190604_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-pk']},
        ),
    ]
